import {writeFileSync, mkdirSync} from 'node:fs';
const out=new URL('./dist/',import.meta.url);mkdirSync(out,{recursive:true});
const button=(label,href,dark=false)=>`<a class="button${dark?' dark':''}" href="${href}">${label}</a>`;
const reveal='class="reveal"';
const portrait=name=>`<figure class="portrait"><img src="assets/pilot-placeholder.svg" alt="" width="100" height="100"><figcaption>Foto de ${name}</figcaption></figure>`;
const stat=(n,label)=>`<div class="stat"><strong>${n}</strong><span>${label}</span></div>`;
const cta=(title,copy,label,href)=>`<section class="section acid cta"><div class="wrap reveal"><div><h2>${title}</h2><p class="lead">${copy}</p></div>${button(label,href,true)}</div></section>`;
const drivers=[{name:'Lucas Andrade',number:'07',city:'São Paulo, SP',quote:'A próxima curva sempre pode ser melhor.'},{name:'Maya Costa',number:'28',city:'Belo Horizonte, MG',quote:'Coragem é acelerar com propósito.'}];
const races=[['14 MAR','INTERLAGOS','São Paulo, Brasil'],['04 ABR','PORTIMÃO','Algarve, Portugal'],['25 ABR','MONZA','Monza, Itália'],['16 MAI','BARCELONA','Barcelona, Espanha']];
function layout(page,title,content){const current=key=>page===key?' aria-current="page"':'';return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#10120f"><title>${title} | Vértice Racing</title><meta name="description" content="Conheça a Vértice Racing: equipe, pilotos e temporada de um projeto conceitual brasileiro de automobilismo."><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Cpath fill='%2310120f' d='M0 0h32v32H0z'/%3E%3Cpath fill='%23d5ff3f' d='M5 7h6l5 17L21 7h6L18 27h-5z'/%3E%3C/svg%3E"><link rel="preload" href="assets/barlow-condensed-bold.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script></head><body><a class="skip" href="#conteudo">Pular para o conteúdo</a><header class="header"><nav class="nav" aria-label="Navegação principal"><a class="brand" href="index.html" aria-label="Vértice Racing — início">V / VÉRTICE</a><button class="menu-toggle" aria-controls="nav-links" aria-expanded="false">Menu</button><div id="nav-links" class="nav-links"><a href="equipe.html"${current('equipe')}>A equipe</a><a href="carro.html"${current('carro')}>O carro</a><a href="pilotos.html"${current('pilotos')}>Pilotos</a><a href="temporada.html"${current('temporada')}>Temporada</a><a href="galeria.html"${current('galeria')}>Galeria</a></div></nav><div class="progress" aria-hidden="true"></div></header><main id="conteudo">${content}</main><footer class="footer"><a href="index.html" class="brand">V / VÉRTICE RACING</a><div class="footer-links"><a href="equipe.html">A EQUIPE</a><a href="pilotos.html">PILOTOS</a><a href="temporada.html">TEMPORADA</a><a href="galeria.html">GALERIA</a></div><p>© 2027 Vértice Racing<br>Equipe e dados fictícios. Projeto conceitual.</p></footer><button class="motion-control" aria-pressed="false">Pausar animações</button></body></html>`;}
const hero=(label,title,copy,extra='')=>`<section class="page-hero"><div class="wrap"><p class="eyebrow"><a href="index.html">INÍCIO</a> / ${label}</p><h1>${title.split('<br>').map((t,i)=>`<span class="hero-line" style="--delay:${i*120}ms">${t}</span>`).join('')}</h1><p class="lead muted">${copy}</p>${extra}</div></section>`;
const home=`<section class="hero-home"><div class="wrap"><div class="stack"><p class="eyebrow">BRASIL NO DNA. O MUNDO NA MIRA.</p><h1><span class="hero-line">NASCIDOS</span><span class="hero-line" style="--delay:100ms">PARA IR</span><span class="hero-line" style="--delay:200ms">ALÉM.</span></h1><p class="lead muted">Cada curva, uma nova possibilidade.<br>Somos a Vértice. E a nossa próxima conquista começa onde o limite termina.</p>${button('Conheça a Vértice','equipe.html')}</div></div></section><div class="manifesto acid"><span>PRECISÃO</span><span>/</span><span>CORAGEM</span><span>/</span><span>EVOLUÇÃO</span><span class="last">/</span><span class="last">VÉRTICE RACING</span></div>
<section class="section"><div class="wrap split"><div class="reveal"><p class="eyebrow">01 / A EQUIPE</p><h2>O LIMITE É SÓ<br>O PONTO DE PARTIDA.</h2></div><div class="stack reveal" style="--delay:120ms"><p class="lead muted">Engenharia que desafia. Pessoas que acreditam. Uma equipe brasileira movida pela vontade de fazer história — dentro e fora das pistas.</p><div class="stats">${stat('02','PILOTOS')}${stat('12','ETAPAS')}${stat('01','MESMA AMBIÇÃO')}</div></div></div></section>
<section id="carro" class="section surface"><div class="wrap split"><div class="reveal"><p class="eyebrow">02 / ENGENHARIA EM MOVIMENTO</p><h2>VR–01. SEM<br>CONCESSÕES.</h2></div><div class="stats specs reveal">${stat('840','CV DE POTÊNCIA')}${stat('620','KG DE PRECISÃO')}${stat('340','KM/H DE ADRENALINA')}</div></div></section>
<section class="section"><div class="wrap"><div class="section-head reveal"><h2>TALENTO QUE ACELERA.</h2><p class="eyebrow">03 / QUEM ESTÁ NO COMANDO</p></div><div class="grid2">${drivers.map((d,i)=>`<a class="driver-card reveal" style="--delay:${i*120}ms" href="pilotos.html#${i?'maya':'lucas'}" aria-label="Conhecer a história de ${d.name}">${portrait(d.name)}<div class="identity"><div><p class="eyebrow">BRASIL / ${i?'PILOTA':'PILOTO'}</p><h3>${d.name.toUpperCase()}</h3><p class="muted">“${d.quote}”</p></div><span class="number">${d.number}</span></div></a>`).join('')}</div></div></section>
<section class="section light"><div class="wrap"><div class="section-head reveal"><h2>A PRÓXIMA CURVA NOS ESPERA.</h2><span class="label">04 / CALENDÁRIO 2027</span></div><div class="race-list">${races.slice(0,3).map((r,i)=>`<a href="temporada.html" class="race-row reveal"><span class="display date">${r[0]}</span><span class="display">${r[1]}</span><span class="location">${r[2]}</span><span class="label">${i?'ETAPA 0'+(i+1):'ABERTURA DA TEMPORADA →'}</span></a>`).join('')}</div></div></section>
<div id="comunidade">${cta('ESSA HISTÓRIA TAMBÉM É SUA.','Entre para a torcida. Viva os bastidores. Acelere com a Vértice.','Acompanhe a temporada','temporada.html')}</div>`;
writeFileSync(new URL('index.html',out),layout('home','Nascidos para ir além',home));
// Secondary pages are written below. All routes are static and usable without JavaScript.
const equipe=hero('A EQUIPE','ANTES DA VELOCIDADE,<br>VEIO A VONTADE.','Uma ideia brasileira. Um sonho coletivo. Uma nova maneira de encarar cada curva.')+`
<figure class="wide-photo reveal"><img data-parallax src="assets/equipe.png" alt="Integrantes da equipe fictícia Vértice preparando o VR-01 nos boxes" width="1536" height="1024"></figure><div class="caption"><span class="lime">NOSSA FORÇA SEMPRE FOI O TIME.</span><span class="muted">VÉRTICE RACING / NOS BASTIDORES</span></div>
<section class="section"><div class="wrap split"><div class="reveal"><p class="eyebrow">01 / NOSSA ORIGEM</p><h2>UM SONHO QUE<br>GANHOU PISTA.</h2></div><div class="reveal"><p class="lead">A Vértice nasceu em 2024, em uma pequena oficina em São Paulo. Um grupo de engenheiros, mecânicos e pilotos decidiu transformar a paixão pelo automobilismo em um projeto com identidade própria.</p><p class="muted">Dos primeiros desenhos ao primeiro teste, cada passo foi construído em conjunto. Hoje, levamos para a pista o mesmo espírito do início: aprender rápido, cuidar de cada detalhe e nunca deixar de acreditar no próximo avanço.</p></div></div></section>
<section class="section surface"><div class="wrap"><h2 class="reveal">PEQUENOS PASSOS. GRANDES ACELERAÇÕES.</h2><div class="grid4 timeline">${[['2024','A PRIMEIRA FAÍSCA','Uma oficina, uma ideia e um time.'],['2025','DO PAPEL AO ASFALTO','O primeiro protótipo ganha vida.'],['2026','CADA DETALHE CONTA','Testes, evolução e formação da dupla.'],['2027','UM NOVO CAPÍTULO','Prontos para a nossa primeira temporada.']].map((m,i)=>`<article class="reveal" style="--delay:${i*90}ms"><strong>${m[0]}</strong><h3>${m[1]}</h3><p>${m[2]}</p></article>`).join('')}</div></div></section>
<section class="section"><div class="wrap grid2"><figure class="value-photo reveal"><img data-parallax src="assets/pista.png" alt="VR-01 em uma pista ao pôr do sol, imagem conceitual" width="1536" height="1024" loading="lazy"></figure><div class="stack reveal"><div><p class="eyebrow">02 / O QUE NOS MOVE</p><h2>VENCER COMEÇA<br>MUITO ANTES DA LARGADA.</h2></div><div class="values">${[['PRECISÃO','Cada detalhe é uma oportunidade de evoluir.'],['CORAGEM','O novo exige vontade de tentar outra vez.'],['UNIÃO','Ninguém cruza a linha de chegada sozinho.']].map(v=>`<div><h3>${v[0]}</h3><p class="muted">${v[1]}</p></div>`).join('')}</div></div></div></section>`+cta('A NOSSA HISTÓRIA ESTÁ SÓ COMEÇANDO.','Conheça quem leva esse sonho para dentro do cockpit.','Voltar ao início','index.html');
writeFileSync(new URL('equipe.html',out),layout('equipe','A equipe',equipe));
const stories=[['DA PRIMEIRA VOLTA<br>AO PRÓXIMO DESAFIO.','Lucas descobriu o automobilismo acompanhando o pai em pistas de kart. Entre fins de semana na oficina e treinos depois da escola, aprendeu que velocidade nasce da repetição — e de ouvir quem está ao seu lado.','A passagem pelas categorias de base moldou seu estilo: leitura de corrida, constância e calma sob pressão. Na Vértice, ele participa dos testes do VR-01 e transforma cada volta em informação para os engenheiros.',['Kart e aprendizado em família.','Experiência nas categorias de base.','Precisão a serviço da Vértice.']],['CORAGEM PARA<br>ABRIR O PRÓPRIO CAMINHO.','Maya começou a correr no kart ainda adolescente. Curiosa sobre tudo o que fazia o carro andar, dividia o tempo entre a pista, os simuladores e as conversas com os mecânicos. Cada descoberta alimentava a vontade de seguir.','Ao avançar para os monopostos, encontrou sua assinatura: adaptação rápida e decisões firmes. Chegou à Vértice para construir um novo capítulo e mostrar que talento cresce quando encontra espaço para acelerar.',['Kart, curiosidade e muita vontade.','O salto para os monopostos.','Uma nova perspectiva no cockpit.']]];
const pilotos=hero('PILOTOS','DUAS HISTÓRIAS.<br>A MESMA SEDE DE IR ALÉM.','Antes do capacete, existem escolhas, desafios e sonhos. Conheça quem transforma a ambição da Vértice em movimento.')+drivers.map((d,i)=>`<section id="${i?'maya':'lucas'}" class="section${i?' surface':''}"><div class="wrap"><div class="profile-grid"><div class="reveal">${portrait(d.name)}<div class="profile-name"><span class="number">${d.number}</span><div><h2>${d.name.toUpperCase()}</h2><p>${d.city.toUpperCase()} / BRASIL</p></div></div></div><div class="profile-story reveal" style="--delay:120ms"><p class="eyebrow">PILOTO ${d.number} / A HISTÓRIA</p><h2>${stories[i][0]}</h2><p>${stories[i][1]}</p><p class="muted">${stories[i][2]}</p></div></div><div class="grid3 milestones">${stories[i][3].map((s,j)=>`<div class="reveal" style="--delay:${j*100}ms"><p class="eyebrow">${['O COMEÇO','A EVOLUÇÃO','AGORA'][j]}</p><p>${s}</p></div>`).join('')}</div><blockquote class="reveal">“${d.quote}”</blockquote></div></section>`).join('')+`<section class="section light"><div class="wrap split reveal"><h2>DIFERENTES NO ESTILO.<br>JUNTOS NO PROPÓSITO.</h2><p class="lead">Lucas traz consistência. Maya, novas perspectivas. Com a engenharia e os mecânicos, os dois constroem uma equipe que aprende a cada volta e cresce em cada desafio.</p></div></section>`+cta('POR TRÁS DOS PILOTOS, UM TIME INTEIRO.','Conheça a história de quem torna cada largada possível.','Conheça a equipe','equipe.html');
writeFileSync(new URL('pilotos.html',out),layout('pilotos','Histórias dos pilotos',pilotos));
const points=[[18,15,12],[12,10,18]];
const temporada=hero('TEMPORADA 2027','CADA ETAPA.<br>UMA NOVA CHANCE.','Acompanhe os circuitos, os resultados e a evolução de Lucas e Maya na pista.','<p class="notice">DADOS DEMONSTRATIVOS / Temporada fictícia simulada após a 3ª etapa. Não são resultados reais.</p>')+`
<section class="acid season-stats"><div class="wrap stats reveal">${stat('03 / 12','ETAPAS CONCLUÍDAS')}${stat('85','PONTOS DA EQUIPE')}${stat('03','PÓDIOS')}${stat('100%','CORRIDAS CONCLUÍDAS')}</div></section>
<section class="section"><div class="wrap"><h2 class="reveal">O CAMINHO DA TEMPORADA.</h2><div class="grid4 circuits">${races.map((r,i)=>`<article class="circuit reveal" style="--delay:${i*90}ms"><div class="meta"><strong>0${i+1}</strong><time datetime="2027-${['03-14','04-04','04-25','05-16'][i]}">${r[0]} 2027</time></div><h3>${r[1]}</h3><p>${r[2]}</p><span class="label">${i===3?'PRÓXIMA ETAPA':'CONCLUÍDA'}</span></article>`).join('')}</div><p class="small muted reveal">Calendário conceitual de 12 etapas. As oito etapas restantes ainda serão anunciadas.</p></div></section>
<section class="section light"><div class="wrap"><h2 class="reveal">RESULTADOS QUE CONTAM A HISTÓRIA.</h2><div class="table-wrap reveal" tabindex="0" role="region" aria-label="Resultados da temporada fictícia"><table><thead><tr><th scope="col">Etapa</th><th scope="col">Lucas Andrade #07</th><th scope="col">Maya Costa #28</th><th scope="col">Pontos da equipe</th></tr></thead><tbody>${[['01 / Interlagos','2º lugar · 18 pts','4º lugar · 12 pts','30 pts'],['02 / Portimão','3º lugar · 15 pts','5º lugar · 10 pts','25 pts'],['03 / Monza','4º lugar · 12 pts','2º lugar · 18 pts','30 pts']].map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="small reveal">Pontuação demonstrativa: 1º 25 · 2º 18 · 3º 15 · 4º 12 · 5º 10. Sem pontos extras.</p></div></section>
<section class="section"><div class="wrap"><h2 class="reveal">DOIS PILOTOS. EVOLUÇÃO A CADA VOLTA.</h2><div class="grid2" style="margin-top:32px">${drivers.map((d,i)=>`<article class="performance-card reveal" style="--delay:${i*120}ms"><div class="performance-title"><span class="number">${d.number}</span><h3>${d.name.toUpperCase()}</h3></div><div class="stats">${stat(i?'40':'45','PONTOS')}${stat(i?'1':'2','PÓDIOS')}${stat(i?'3,7':'3,0','POSIÇÃO MÉDIA')}</div><p class="small muted">PONTOS POR ETAPA / ESCALA DE 0 A 25</p><div class="bars">${points[i].map((p,j)=>`<div class="bar-row" aria-label="Etapa ${j+1}: ${p} pontos de 25"><span>0${j+1}</span><div class="track" aria-hidden="true"><div class="fill" style="--value:${p/25*100}%"></div></div><span>${p}</span></div>`).join('')}</div></article>`).join('')}</div><p class="small muted performance-note reveal">Ambos concluíram 3 de 3 corridas. Média calculada a partir das posições finais acima.</p></div></section>`+cta('PRÓXIMA PARADA: BARCELONA.','16 de maio de 2027 / Etapa 04 / Calendário fictício','Conheça os pilotos','pilotos.html');
writeFileSync(new URL('temporada.html',out),layout('temporada','Temporada 2027',temporada));
const carro=`<section class="section car-hero"><div class="wrap stack"><p class="eyebrow">O CARRO / TEMPORADA 2027</p><h1 class="hero-line">VR–01. FEITO PARA IR ALÉM.</h1><p class="lead muted">Cada curva começa no detalhe. Conheça o carro que transforma a ambição da Vértice em velocidade.</p><figure class="car-track reveal"><img src="assets/pista.png" width="1536" height="1024" alt="Carro da Vértice na pista, em imagem ilustrativa"><figcaption class="small muted">Imagem ilustrativa do conceito de competição da Vértice.</figcaption></figure></div></section>
<section class="section acid car-specs"><div class="wrap stack reveal"><h2>POTÊNCIA, LEVEZA E VELOCIDADE.</h2><div class="stats">${stat('840 CV','Potência conceitual')}${stat('620 KG','Massa conceitual')}${stat('340 KM/H','Velocidade máxima estimada')}</div></div></section>
<section class="section"><div class="wrap car-grid"><figure class="car-drawing reveal"><img src="assets/vr01.svg" width="660" height="530" alt="Vista técnica superior do monoposto VR-01"></figure><div class="stack reveal"><p class="eyebrow">PROJETADO PARA EVOLUIR</p><h2>PRECISÃO EM<br>CADA DETALHE.</h2><div class="car-detail"><h3>Aerodinâmica</h3><p class="muted">Asas e carroceria trabalham em conjunto para buscar estabilidade nas curvas e eficiência nas retas.</p></div><div class="car-detail"><h3>Estrutura e equilíbrio</h3><p class="muted">Um conceito leve, com distribuição de massa pensada para respostas precisas aos comandos de Lucas e Maya.</p></div><div class="car-detail"><h3>Acerto de pista</h3><p class="muted">Suspensão, pneus e balanço do carro são ajustados a cada circuito a partir das sensações dos pilotos.</p></div></div></div></section>
<section class="section light"><div class="wrap car-grid"><div class="stack reveal"><p class="label">DO BOX À PISTA</p><h2>UMA TEMPORADA.<br>EVOLUÇÃO CONTÍNUA.</h2><p class="lead">O VR–01 é a base do nosso projeto para 2027. A cada etapa, a equipe cruza os dados de pista com o relato dos pilotos para definir os próximos ajustes.</p><p>O foco está na consistência: encontrar um carro previsível nas curvas, eficiente nas retas e equilibrado ao longo da corrida.</p></div><figure class="car-garage reveal"><img src="assets/equipe.png" width="1536" height="1024" loading="lazy" alt="Equipe trabalhando no carro dentro dos boxes"></figure></div></section>
<section class="section acid"><div class="wrap stack reveal"><h2>VEJA O VR–01 EM AÇÃO.</h2><p class="lead">Conheça os circuitos, os resultados e a performance dos nossos pilotos.</p>${button('Acompanhar a temporada','temporada.html',true)}<p class="small">Equipe e temporada fictícias. Especificações conceituais e imagens ilustrativas.</p></div></section>`;
writeFileSync(new URL('carro.html',out),layout('carro','O carro — VR–01',carro));


const galleryPhotos=[['pista.png','NA PISTA','O VR–01 encontra o asfalto','Carro preto e verde-lima acelerando no circuito'],['equipe.png','BASTIDORES','A corrida começa nos boxes','Mecânicos da equipe preparando o carro'],['pitstop.png','PIT STOP','Cada segundo conta','Equipe trocando os pneus do monoposto'],['celebracao.png','EQUIPE','Uma conquista de todos','Pilotos e mecânicos celebrando com um troféu']];
const galeria=hero('GALERIA / TEMPORADA 2027','A TEMPORADA.<br>POR OUTROS ÂNGULOS.','A velocidade, os bastidores e as pessoas que fazem cada etapa acontecer.')+`<section class="section gallery-section"><div class="wrap"><p class="small muted gallery-note">Momentos ilustrativos de uma temporada fictícia. Fotografias geradas por IA.</p><div class="gallery-grid">${galleryPhotos.map(([src,tag,title,alt],i)=>`<figure class="gallery-card reveal" style="--delay:${i%2*100}ms"><a href="assets/${src}" target="_blank" rel="noopener" aria-label="Ampliar: ${title}"><img src="assets/${src}" alt="${alt}" width="1536" height="1024" loading="${i<2?'eager':'lazy'}"></a><figcaption><p class="eyebrow">${tag}</p><h2>${title}</h2><span class="small muted">TEMPORADA 2027 / ${String(i+1).padStart(2,'0')}</span></figcaption></figure>`).join('')}</div></div></section>`+cta('CADA FOTO, UM CAPÍTULO.','Acompanhe o que acontece em cada etapa da Vértice.','Ver a temporada','temporada.html');
writeFileSync(new URL('galeria.html',out),layout('galeria','Galeria',galeria));


