import {writeFileSync, mkdirSync} from 'node:fs';
const out=new URL('./dist/',import.meta.url);mkdirSync(out,{recursive:true});
const button=(label,href,dark=false)=>`<a class="button${dark?' dark':''}" href="${href}">${label}</a>`;
const reveal='class="reveal"';
const portrait=name=>`<figure class="portrait portrait-photo"><img src="assets/${name==='Lucas Andrade'?'lucas-andrade':'maya-costa'}.png" alt="Illustrative portrait of ${name} wearing a Vértice racing suit" width="1536" height="1024" loading="lazy"></figure>`;
const stat=(n,label)=>`<div class="stat"><strong>${n}</strong><span>${label}</span></div>`;
const cta=(title,copy,label,href)=>`<section class="section acid cta"><div class="wrap reveal"><div><h2>${title}</h2><p class="lead">${copy}</p></div>${button(label,href,true)}</div></section>`;
const drivers=[{name:'Lucas Andrade',number:'07',city:'São Paulo, SP',quote:'There is always more to find in the next corner.'},{name:'Maya Costa',number:'28',city:'Belo Horizonte, MG',quote:'Courage means driving with purpose.'}];
const races=[['14 MAR','INTERLAGOS','São Paulo, Brazil'],['04 APR','PORTIMÃO','Algarve, Portugal'],['25 APR','MONZA','Monza, Italy'],['16 MAY','BARCELONA','Barcelona, Spain']];
function layout(page,title,content){const current=key=>page===key?' aria-current="page"':'';return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#10120f"><title>${title} | Vértice Racing</title><meta name="description" content="Discover Vértice Racing: the team, drivers, car and season of a fictional Brazilian motorsport team."><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Cpath fill='%2310120f' d='M0 0h32v32H0z'/%3E%3Cpath fill='%23d5ff3f' d='M5 7h6l5 17L21 7h6L18 27h-5z'/%3E%3C/svg%3E"><link rel="preload" href="assets/barlow-condensed-bold.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="styles.css?v=transition-logo-1500-v2"><script src="app.js?v=transition-logo-1500-v2" defer></script></head><body><a class="skip" href="#conteudo">Skip to content</a><header class="header"><nav class="nav" aria-label="Main navigation"><a class="brand" href="index.html" aria-label="Vértice Racing — home">V / VÉRTICE</a><button class="menu-toggle" aria-controls="nav-links" aria-expanded="false">Menu</button><div id="nav-links" class="nav-links"><a href="equipe.html"${current('equipe')}>The team</a><a href="carro.html"${current('carro')}>The car</a><a href="pilotos.html"${current('pilotos')}>Drivers</a><a href="temporada.html"${current('temporada')}>Season</a><a href="galeria.html"${current('galeria')}>Gallery</a></div></nav><div class="progress" aria-hidden="true"></div></header><main id="conteudo">${content}</main><footer class="footer"><a href="index.html" class="brand">V / VÉRTICE RACING</a><div class="footer-links"><a href="equipe.html">THE TEAM</a><a href="pilotos.html">DRIVERS</a><a href="temporada.html">SEASON</a><a href="galeria.html">GALLERY</a></div><p>© 2027 Vértice Racing<br>Fictional team and data. A concept project.</p></footer></body></html>`;}
const hero=(label,title,copy,extra='')=>`<section class="page-hero"><div class="wrap"><p class="eyebrow"><a href="index.html">HOME</a> / ${label}</p><h1>${title.split('<br>').map((t,i)=>`<span class="hero-line" style="--delay:${i*120}ms">${t}</span>`).join('')}</h1><p class="lead muted">${copy}</p>${extra}</div></section>`;
const home=`<section class="hero-home"><div class="wrap"><div class="stack"><p class="eyebrow">BRAZILIAN ROOTS. GLOBAL AMBITION.</p><h1><span class="hero-line">BORN</span><span class="hero-line" style="--delay:100ms">TO GO</span><span class="hero-line" style="--delay:200ms">BEYOND.</span></h1><p class="lead muted">Every corner brings a new possibility.<br>We are Vértice. Our next breakthrough begins beyond the limit.</p>${button('Discover Vértice','equipe.html')}</div></div></section><div class="manifesto acid"><span>PRECISION</span><span>/</span><span>COURAGE</span><span>/</span><span>PROGRESS</span><span class="last">/</span><span class="last">VÉRTICE RACING</span></div>
<section class="section"><div class="wrap split"><div class="reveal"><p class="eyebrow">01 / THE TEAM</p><h2>THE LIMIT IS JUST<br>THE STARTING LINE.</h2></div><div class="stack reveal" style="--delay:120ms"><p class="lead muted">Engineering that challenges convention. People who believe. A Brazilian team driven to make history — on and off the track.</p><div class="stats">${stat('02','DRIVERS')}${stat('12','ROUNDS')}${stat('01','SHARED AMBITION')}</div></div></div></section>
<section id="carro" class="section surface"><div class="wrap split"><div class="reveal"><p class="eyebrow">02 / ENGINEERING IN MOTION</p><h2>VR–01. NO<br>COMPROMISE.</h2></div><div class="stats specs reveal">${stat('840','PS OF POWER')}${stat('620','KG OF PRECISION')}${stat('340','KM/H OF ADRENALINE')}</div></div></section>
<section class="section"><div class="wrap"><div class="section-head reveal"><h2>TALENT AT FULL THROTTLE.</h2><p class="eyebrow">03 / BEHIND THE WHEEL</p></div><div class="grid2">${drivers.map((d,i)=>`<a class="driver-card reveal" style="--delay:${i*120}ms" href="pilotos.html#${i?'maya':'lucas'}" aria-label="Discover the story of ${d.name}">${portrait(d.name)}<div class="identity"><div><p class="eyebrow">BRAZIL / DRIVER</p><h3>${d.name.toUpperCase()}</h3><p class="muted">“${d.quote}”</p></div><span class="number">${d.number}</span></div></a>`).join('')}</div></div></section>
<section class="section light"><div class="wrap"><div class="section-head reveal"><h2>THE NEXT CORNER AWAITS.</h2><span class="label">04 / 2027 CALENDAR</span></div><div class="race-list">${races.slice(0,3).map((r,i)=>`<a href="temporada.html" class="race-row reveal"><span class="display date">${r[0]}</span><span class="display">${r[1]}</span><span class="location">${r[2]}</span><span class="label">${i?'ROUND 0'+(i+1):'SEASON OPENER →'}</span></a>`).join('')}</div></div></section>
<div id="comunidade">${cta('YOU ARE PART OF THIS STORY.','Join the fans. Go behind the scenes. Follow every lap with Vértice.','Follow the season','temporada.html')}</div>`;
writeFileSync(new URL('index.html',out),layout('home','Born to go beyond',home));
// Secondary pages are written below. All routes are static and usable without JavaScript.
const equipe=hero('THE TEAM','BEFORE THE SPEED,<br>CAME THE DRIVE.','A Brazilian idea. A shared dream. A fresh approach to every corner.')+`
<figure class="wide-photo reveal"><img data-parallax src="assets/equipe.png" alt="Members of the fictional Vértice team preparing the VR-01 in the garage" width="1536" height="1024"></figure><div class="caption"><span class="lime">OUR STRENGTH HAS ALWAYS BEEN OUR TEAM.</span><span class="muted">VÉRTICE RACING / BEHIND THE SCENES</span></div>
<section class="section"><div class="wrap split"><div class="reveal"><p class="eyebrow">01 / OUR ORIGINS</p><h2>A DREAM THAT<br>FOUND ITS TRACK.</h2></div><div class="reveal"><p class="lead">Vértice began in 2024 in a small workshop in São Paulo. A group of engineers, mechanics and drivers set out to turn their passion for motorsport into a team with an identity of its own.</p><p class="muted">From the first sketches to the first test, every step was a shared effort. Today, we bring that same spirit to the track: learn quickly, care about every detail and keep believing in the next breakthrough.</p></div></div></section>
<section class="section surface"><div class="wrap"><h2 class="reveal">SMALL STEPS. SERIOUS MOMENTUM.</h2><div class="grid4 timeline">${[['2024','THE FIRST SPARK','One workshop, one idea and one team.'],['2025','FROM SKETCH TO TRACK','Our first prototype comes to life.'],['2026','EVERY DETAIL COUNTS','Testing, development and our driver lineup.'],['2027','A NEW CHAPTER','Ready for our first season.']].map((m,i)=>`<article class="reveal" style="--delay:${i*90}ms"><strong>${m[0]}</strong><h3>${m[1]}</h3><p>${m[2]}</p></article>`).join('')}</div></div></section>
<section class="section"><div class="wrap grid2"><figure class="value-photo reveal"><img data-parallax src="assets/pista.png" alt="Concept image of the VR-01 on a circuit at sunset" width="1536" height="1024" loading="lazy"></figure><div class="stack reveal"><div><p class="eyebrow">02 / WHAT DRIVES US</p><h2>WINNING BEGINS<br>LONG BEFORE THE LIGHTS GO OUT.</h2></div><div class="values">${[['PRECISION','Every detail is a chance to improve.'],['COURAGE','Progress takes the courage to try again.'],['UNITY','No one reaches the finish line alone.']].map(v=>`<div><h3>${v[0]}</h3><p class="muted">${v[1]}</p></div>`).join('')}</div></div></div></section>`+cta('OUR STORY IS JUST GETTING STARTED.','Meet the people who carry this dream into the cockpit.','Back to home','index.html');
writeFileSync(new URL('equipe.html',out),layout('equipe','The team',equipe));
const stories=[['FROM THE FIRST LAP<br>TO THE NEXT CHALLENGE.','Lucas discovered motorsport at karting tracks with his father. Between weekends in the workshop and practice after school, he learned that speed comes from repetition — and listening to the people around you.','The junior categories shaped his approach: race awareness, consistency and composure under pressure. At Vértice, he helps test the VR-01, turning every lap into useful feedback for the engineers.',['Karting and learning with family.','Experience in the junior categories.','Putting precision to work for Vértice.']],['THE COURAGE TO<br>FIND HER OWN WAY.','Maya started karting as a teenager. Curious about everything that made a car move, she split her time between the track, simulators and conversations with mechanics. Every discovery fueled her drive to keep going.','Moving into single-seaters, she found her signature style: quick adaptation and decisive moves. She joined Vértice to write a new chapter and show what talent can achieve when given room to grow.',['Karting, curiosity and determination.','The step up to single-seaters.','A fresh perspective in the cockpit.']]];
const pilotos=hero('DRIVERS','TWO STORIES.<br>ONE DRIVE TO GO BEYOND.','Behind every helmet are choices, challenges and dreams. Meet the drivers who put the ambition of Vértice into motion.')+drivers.map((d,i)=>`<section id="${i?'maya':'lucas'}" class="section${i?' surface':''}"><div class="wrap"><div class="profile-grid"><div class="reveal">${portrait(d.name)}<div class="profile-name"><span class="number">${d.number}</span><div><h2>${d.name.toUpperCase()}</h2><p>${d.city.toUpperCase()} / BRAZIL</p></div></div></div><div class="profile-story reveal" style="--delay:120ms"><p class="eyebrow">DRIVER ${d.number} / THE STORY</p><h2>${stories[i][0]}</h2><p>${stories[i][1]}</p><p class="muted">${stories[i][2]}</p></div></div><div class="grid3 milestones">${stories[i][3].map((s,j)=>`<div class="reveal" style="--delay:${j*100}ms"><p class="eyebrow">${['THE BEGINNING','THE PROGRESS','TODAY'][j]}</p><p>${s}</p></div>`).join('')}</div><blockquote class="reveal">“${d.quote}”</blockquote></div></section>`).join('')+`<section class="section light"><div class="wrap split reveal"><h2>DIFFERENT STYLES.<br>A SHARED PURPOSE.</h2><p class="lead">Lucas brings consistency. Maya brings fresh perspectives. Together with the engineers and mechanics, they build a team that learns with every lap and grows through every challenge.</p></div></section>`+cta('BEHIND EVERY DRIVER, AN ENTIRE TEAM.','Discover the story of the people who make every race start possible.','Meet the team','equipe.html');
writeFileSync(new URL('pilotos.html',out),layout('pilotos','Driver stories',pilotos));
const points=[[18,15,12],[12,10,18]];
const temporada=hero('2027 SEASON','EVERY ROUND.<br>A NEW OPPORTUNITY.','Explore the circuits, results and progress of Lucas and Maya on track.','<p class="notice">DEMO DATA / A fictional season simulated after Round 3. These are not real results.</p>')+`
<section class="acid season-stats"><div class="wrap stats reveal">${stat('03 / 12','ROUNDS COMPLETED')}${stat('85','TEAM POINTS')}${stat('03','PODIUMS')}${stat('100%','RACES FINISHED')}</div></section>
<section class="section"><div class="wrap"><h2 class="reveal">THE ROAD THROUGH THE SEASON.</h2><div class="grid4 circuits">${races.map((r,i)=>`<article class="circuit reveal" style="--delay:${i*90}ms"><div class="meta"><strong>0${i+1}</strong><time datetime="2027-${['03-14','04-04','04-25','05-16'][i]}">${r[0]} 2027</time></div><h3>${r[1]}</h3><p>${r[2]}</p><span class="label">${i===3?'NEXT ROUND':'COMPLETED'}</span></article>`).join('')}</div><p class="small muted reveal">A concept calendar of 12 rounds. The remaining eight rounds are yet to be announced.</p></div></section>
<section class="section light"><div class="wrap"><h2 class="reveal">RESULTS THAT TELL THE STORY.</h2><div class="table-wrap reveal" tabindex="0" role="region" aria-label="Fictional season results"><table><thead><tr><th scope="col">Round</th><th scope="col">Lucas Andrade #07</th><th scope="col">Maya Costa #28</th><th scope="col">Team points</th></tr></thead><tbody>${[['01 / Interlagos','2nd place · 18 pts','4th place · 12 pts','30 pts'],['02 / Portimão','3rd place · 15 pts','5th place · 10 pts','25 pts'],['03 / Monza','4th place · 12 pts','2nd place · 18 pts','30 pts']].map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="small reveal">Demo scoring: 1st 25 · 2nd 18 · 3rd 15 · 4th 12 · 5th 10. No bonus points.</p></div></section>
<section class="section"><div class="wrap"><h2 class="reveal">TWO DRIVERS. PROGRESS ON EVERY LAP.</h2><div class="grid2" style="margin-top:32px">${drivers.map((d,i)=>`<article class="performance-card reveal" style="--delay:${i*120}ms"><div class="performance-title"><span class="number">${d.number}</span><h3>${d.name.toUpperCase()}</h3></div><div class="stats">${stat(i?'40':'45','POINTS')}${stat(i?'1':'2','PODIUMS')}${stat(i?'3.7':'3.0','AVERAGE FINISH')}</div><p class="small muted">POINTS PER ROUND / SCALE OF 0 TO 25</p><div class="bars">${points[i].map((p,j)=>`<div class="bar-row" aria-label="Round ${j+1}: ${p} points out of 25"><span>0${j+1}</span><div class="track" aria-hidden="true"><div class="fill" style="--value:${p/25*100}%"></div></div><span>${p}</span></div>`).join('')}</div></article>`).join('')}</div><p class="small muted performance-note reveal">Both drivers finished 3 out of 3 races. Averages are calculated from the finishing positions above.</p></div></section>`+cta('NEXT STOP: BARCELONA.','May 16, 2027 / Round 04 / Fictional calendar','Meet the drivers','pilotos.html');
writeFileSync(new URL('temporada.html',out),layout('temporada','2027 season',temporada));
const carro=`<section class="section car-hero"><div class="wrap stack"><p class="eyebrow">THE CAR / 2027 SEASON</p><h1 class="hero-line">VR–01. BUILT TO GO BEYOND.</h1><p class="lead muted">Every corner begins with the details. Discover the car that turns the ambition of Vértice into speed.</p><figure class="car-track reveal"><img src="assets/pista.png" width="1536" height="1024" alt="Illustrative image of the Vértice car on track"><figcaption class="small muted">Illustrative image of the Vértice racing concept.</figcaption></figure></div></section>
<section class="section acid car-specs"><div class="wrap stack reveal"><h2>POWER, LIGHTNESS AND SPEED.</h2><div class="stats">${stat('840 PS','Concept power (metric hp)')}${stat('620 KG','Concept mass')}${stat('340 KM/H','Estimated top speed')}</div></div></section>
<section class="section"><div class="wrap car-grid"><figure class="car-drawing reveal"><img src="assets/vr01.svg" width="660" height="530" alt="Technical top view of the VR-01 single-seater"></figure><div class="stack reveal"><p class="eyebrow">DESIGNED TO EVOLVE</p><h2>PRECISION IN<br>EVERY DETAIL.</h2><div class="car-detail"><h3>Aerodynamics</h3><p class="muted">The wings and bodywork work together to deliver stability through corners and efficiency on the straights.</p></div><div class="car-detail"><h3>Structure and balance</h3><p class="muted">A lightweight concept with weight distribution designed to respond precisely to every input from Lucas and Maya.</p></div><div class="car-detail"><h3>Track setup</h3><p class="muted">Suspension, tires and car balance are fine-tuned for each circuit using driver feedback.</p></div></div></div></section>
<section class="section light"><div class="wrap car-grid"><div class="stack reveal"><p class="label">FROM GARAGE TO GRID</p><h2>ONE SEASON.<br>CONSTANT DEVELOPMENT.</h2><p class="lead">The VR–01 is the foundation of our 2027 project. At every round, the team combines track data with driver feedback to plan the next adjustments.</p><p>The focus is consistency: a car that feels predictable in corners, efficient on the straights and balanced throughout the race.</p></div><figure class="car-garage reveal"><img src="assets/equipe.png" width="1536" height="1024" loading="lazy" alt="Team members working on the car in the garage"></figure></div></section>
<section class="section acid"><div class="wrap stack reveal"><h2>SEE THE VR–01 IN ACTION.</h2><p class="lead">Explore the circuits, results and driver performances.</p>${button('Follow the season','temporada.html',true)}<p class="small">Fictional team and season. Concept specifications and illustrative images.</p></div></section>`;
writeFileSync(new URL('carro.html',out),layout('carro','The car — VR–01',carro));


const galleryPhotos=[['pista.png','ON TRACK','The VR–01 hits the track','Black and lime-green racing car accelerating on the circuit'],['pilotas-telemetria.png','BEHIND THE SCENES','Drivers behind the scenes','Two female drivers reviewing telemetry in the garage'],['pitstop.png','PIT STOP','Every second counts','The pit crew changing the tires of a single-seater'],['pilotas-celebracao.png','TEAM','A victory we share','Female drivers and a team member celebrating with a trophy']];
const galeria=hero('GALLERY / 2027 SEASON','THE SEASON.<br>FROM EVERY ANGLE.','The speed, the moments behind the scenes and the people who make every race happen.')+`<section class="section gallery-section"><div class="wrap"><p class="small muted gallery-note">Illustrative moments from a fictional season. AI-generated photographs.</p><div class="gallery-grid">${galleryPhotos.map(([src,tag,title,alt],i)=>`<figure class="gallery-card reveal" style="--delay:${i%2*100}ms"><a href="assets/${src}" target="_blank" rel="noopener" aria-label="Enlarge: ${title}"><img src="assets/${src}" alt="${alt}" width="1536" height="1024" loading="${i<2?'eager':'lazy'}"></a><figcaption><p class="eyebrow">${tag}</p><h2>${title}</h2><span class="small muted">2027 SEASON / ${String(i+1).padStart(2,'0')}</span></figcaption></figure>`).join('')}</div></div></section>`+cta('EVERY PHOTO, A CHAPTER.','Follow every round of the Vértice season.','View the season','temporada.html');
writeFileSync(new URL('galeria.html',out),layout('galeria','Gallery',galeria));


